//
//  string_price_alert.h
//  Tokopedia
//
//  Created by Tokopedia on 5/22/15.
//  Copyright (c) 2015 TOKOPEDIA. All rights reserved.
//

#ifndef Tokopedia_string_price_alert_h
#define Tokopedia_string_price_alert_h
#define CGetPriceAlert @"get_price_alert"
#define CDeletePriceAlert @"delete_product_price_alert"
#define CDeleteCatalogPriceAlert @"delete_catalog_price_alert"
#define CGetPriceAlertDetail @"get_price_alert_detail"
#define CAction @"action"
#define CEditPriceAlert @"edit_inbox_price_alert"
#define CAddPriceAlert @"add_product_price_alert"
#define CAddCatalogPriceAlert @"add_catalog_price_alert"
#define CDeleteCatalogPriceAlert @"delete_catalog_price_alert"
#define CInboxPriceAlert @"inbox-price-alert.pl"
#define CPriceAlertPL @"pricealert.pl"
#define CDepartment @"department"
#define CBreadCrumb @"breadcrumb"
#define CPaging @"paging"
#define CPage @"page"
#define CList @"list"
#define CCondition @"condition"
#define CSort @"order_by"


#define CStringKecepatan @"Kecepatan"
#define CStringAKurasi @"Akurasi"
#define CStringPelayanan @"Pelayanan"
#define CStringAllPrice @"Semua Harga"
#define CStringSort @"Urutkan"
#define CstringFilter @"Filter"
#define CStringCategory @"Kategori"
#define CStringSuccessRemovePriceAlert @"Anda telah berhasil menghapus notifikasi harga"
#define CStringConfirmDeleteCatalog @"Apakah Anda yakin menghapus notifikasi harga ini?"
#define CStringYa @"Ya"
#define CStringTidak @"Tidak"
#define CStringPembaruanTerakhir @"Pembaruan Terakhir"
#define CStringProductTerjual @"Produk Terjual"
#define CStringUlasan @"Ulasan"
#define CStringHargaTerendah @"Harga Terendah"
#define CStringHargaTertinggi @"Harga Tertinggi"
#define CStringSemuaKondisi @"Semua Kondisi"
#define CStringBaru @"Baru"
#define CStringBekas @"Bekas"
#define CStringFailedBuyProduct @"Gagal beli produk. Silahkan coba lagi"
#define CStringNoInternet @"Pastikan jaringan anda tersedia"
#define CStringSave @"Simpan"
#define CStringFillPrice @"Masukkan Harga"
#define CStringFailedAddCatalogPriceAlert @"Gagal menambah notifikasi harga katalog"
#define CStringFailedAddPriceAlert @"Gagal menambah notifikasi harga produk"
#define CStringFailedEditPriceAlert @"Gagal mengubah notifikasi harga produk"
#define CStringFailedDeletePriceAlert @"Gagal menghapus notifikasi harga"
#define CStringWaitLoading @"Silahkan coba lagi, Ada proses yang sedang di eksekusi"
#define CStringAllDepartment @"Semua Department"
#define CStringDepartment @"Department"
#define CStringSelesai @"Selesai"
#define CStringPriceAlert @"Price Alert"
#define CStringNotifikasiAlert @"Notifikasi Alert"
#define CStringBatal @"Batal"
#define CStringBack @"Back"
#define CStringUbah @"Ubah"
#define CStringNotificationHarga @"Notifikasi Harga"
#define CStringSuccessEditPriceAlert @"Anda telah berhasil memperbaharui notifikasi harga produk"
#define CStringSuccessAddPrice @"Anda telah berhasil menambah notifikasi harga produk"
#define CStringSuccessEditPriceCatalog @"Anda telah berhasil memperbaharui notifikasi katalog"
#define CStringSuccessAddPriceCatalog @"Anda telah berhasil menambah notifikasi katalog"
#endif
