//
//  stringproduct.h
//  Tokopedia
//
//  Created by IT Tkpd on 12/10/14.
//  Copyright (c) 2014 TOKOPEDIA. All rights reserved.
//

#ifndef Tokopedia_stringproduct_h
#define Tokopedia_stringproduct_h

typedef enum
{
    TYPE_ADD_EDIT_PRODUCT_DEFAULT = 0,
    TYPE_ADD_EDIT_PRODUCT_ADD,
    TYPE_ADD_EDIT_PRODUCT_EDIT
}TYPE_ADD_EDIT_PRODUCT;

typedef enum
{
    BUTTON_PRODUCT_DEFAULT = 0,
    BUTTON_PRODUCT_CATEGORY = 10,
    BUTTON_PRODUCT_PRICE_CURRENCY = 11,
    BUTTON_PRODUCT_WEIGHT_UNIT = 12,
    
    BUTTON_PRODUCT_INSURANCE = 10,
    BUTTON_PRODUCT_ETALASE = 11,
    BUTTON_PRODUCT_ETALASE_DETAIL = 12,
    BUTTON_PRODUCT_CONDITION = 13,
    BUTTON_PRODUCT_RETURNABLE_NOTE = 14,
    
    BUTTON_PRODUCT_ADD_WHOLESALE = 10,
    
    BUTTON_PRODUCT_DELETE_PRODUCT_IMAGE = 10,
    BUTTON_PRODUCT_UPDATE_PRODUCT_IMAGE = 11
    
}BUTTON_PRODUCT;

typedef enum
{
    SWITCH_PRODUCT_DEFAULT = 0,
    SWITCH_PRODUCT_DEFAULT_IMAGE = 10
}SWITCH_PRODUCT;


typedef enum
{
    BARBUTTON_PRODUCT_DEFAULT = 0,
    BARBUTTON_PRODUCT_BACK = 10,
    BARBUTTON_PRODUCT_SAVE = 11,
    BARBUTTON_PRODUCT_NEXT = 12
}BARBUTTON_PRODUCT;

typedef enum
{
    GESTURE_PRODUCT_DEFAULT = 0,
    GESTURE_PRODUCT_EDIT_WHOLESALE = 11
}GESTURE_PRODUCT;

#define DATA_NAME_KEY @"name"
#define DATA_VALUE_KEY @"value"

#define API_UPLOAD_PRODUCT_IMAGE_DATA_NAME @"fileToUpload"

#define WEIGHT_UNIT_ID_GRAM 1
#define MINIMUM_WEIGHT_GRAM 1
#define MAXIMUM_WEIGHT_GRAM 35000

#define WEIGHT_UNIT_ID_KILOGRAM 2
#define MINIMUM_WEIGHT_KILOGRAM 1
#define MAXIMUM_WEIGHT_KILOGRAM 35

#define PRICE_CURRENCY_ID_RUPIAH 1
#define MINIMUM_PRICE_RUPIAH 100
#define MAXIMUM_PRICE_RUPIAH 50000000

#define PRICE_CURRENCY_ID_USD 2
#define MINIMUM_PRICE_USD 1
#define MAXIMUM_PRICE_USD 4000

#define RETURNABLE_YES_ID 1
#define RETURNABLE_NO_ID 2
#define PRODUCT_WAREHOUSE_NOTSET_ID 0
#define PRODUCT_WAREHOUSE_YES_ID 2
#define PRODUCT_WAREHOUSE_NO_ID 1
#define PRODUCT_CONDITION_NOTSET_ID 0
#define PRODUCT_CONDITION_NEW_ID 1
#define PRODUCT_CONDITION_SECOND_ID 2

#define BUTTON_DELETE_TITLE @"Delete"
#define BUTTON_EDIT_PRODUCT @"  Edit  "
#define BUTTON_DUPLICATE_PRODUCT @" Salin "
#define BUTTON_MOVE_ETALASE @"Ubah\nEtalase"
#define BUTTON_MOVETO_WAREHOUSE_TITLE @"Pindah ke\nGudang"

#define CONFIRMATIONMESSAGE_DELETE_PRODUCT_IMAGE @"Apakah Anda ingin menghapus gambar ini?"

#define SUCCESSMESSAGE_ADD_PRODUCT @"Sukses menambahkan product."
#define SUCCESSMESSAGE_EDIT_PRODUCT @"Sukses Merubah product."

#define ERRORMESSAGE_NULL_PRODUCT_NAME @"Nama Produk harus diisi."
#define ERRORMESSAGE_NULL_PRICE @"Harga harus diisi."
#define ERRORMESSAGE_NULL_CATEGORY @"Kategori tidak benar."
#define ERRORMESSAGE_NULL_IMAGE @"Gambar harus diisi."
#define ERRORMESSAGE_INVALID_PRICE_RUPIAH @"Rentang Harga 100 - 50000000."
#define ERRORMESSAGE_INVALID_PRICE_USD @"Rentang Harga 1 - 4000."
#define ERRORMESSAGE_INVALID_WEIGHT_GRAM @"Berat harus diisi antara 1 - 35000."
#define ERRORMESSAGE_INVALID_WEIGHT_KILOGRAM @"Berat harus diisi antara 1 - 35."
#define ERRORMESSAGE_INVALID_QUANTITY_WHOLESALE @"Total produk tidak valid."
#define ERRORMESSAGE_INVALID_QUANTITY_MINIMUM_WHOLESALE_COMPARE_MINIMUM_ORDER @"Jumlah barang grosir harus lebih besar dari minimum pemesanan"
#define ERRORMESSAGE_INVALID_PRICE_WHOLESALE @"Harga harus lebih murah dari harga grosir sebelumnya."
#define ERRORMESSAGE_INVALID_PRICE_WHOLESALE_COMPARE_NET @"Harga grosir harus lebih murah dari harga pas."
#define ERRORMESSAGE_MAXIMAL_WHOLESALE_LIST @"Hanya boleh menambahkan 5 harga grosir"

#define ARRAY_PRICE_CURRENCY_GOLD_MERCHANT @[@{DATA_NAME_KEY:@"Rp", DATA_VALUE_KEY:@(1)}, @{DATA_NAME_KEY:@"US$", DATA_VALUE_KEY:@(2)}]
#define ARRAY_WEIGHT_UNIT @[@{DATA_NAME_KEY:@"Gram (g)", DATA_VALUE_KEY:@(1)}, @{DATA_NAME_KEY:@"Kilogram (kg)", DATA_VALUE_KEY:@(2)}]
#define ARRAY_PRODUCT_INSURACE @[@{DATA_NAME_KEY:@"Optional", DATA_VALUE_KEY:@(1)}, @{DATA_NAME_KEY:@"Yes", DATA_VALUE_KEY:@(2)}]
#define ARRAY_PRODUCT_CONDITION @[@{DATA_NAME_KEY:@"Baru", DATA_VALUE_KEY:@(PRODUCT_CONDITION_NEW_ID)}, @{DATA_NAME_KEY:@"Bekas", DATA_VALUE_KEY:@(PRODUCT_CONDITION_SECOND_ID)}]
#define ARRAY_PRODUCT_MOVETO_ETALASE @[@{DATA_NAME_KEY:@"Gudang", DATA_VALUE_KEY:@(2)}, @{DATA_NAME_KEY:@"Etalase", DATA_VALUE_KEY:@(1)}]
#define ARRAY_PRODUCT_RETURNABLE @[@{DATA_NAME_KEY:@"Not Set", DATA_VALUE_KEY:@(0)}, @{DATA_NAME_KEY:@"Yes", DATA_VALUE_KEY:@(RETURNABLE_YES_ID)}, @{DATA_NAME_KEY:@"No", DATA_VALUE_KEY:@(RETURNABLE_NO_ID)}]
#define ARRAY_PRODUCT_WAREHOUSE @[@{DATA_NAME_KEY:@"Yes", DATA_VALUE_KEY:@(PRODUCT_WAREHOUSE_YES_ID)},@{DATA_NAME_KEY:@"No", DATA_VALUE_KEY:@(PRODUCT_WAREHOUSE_NO_ID)}]

#endif
