//
//  AnalyticsString.h
//  Tokopedia
//
//  Created by Kenneth Vincent on 10/4/16.
//  Copyright © 2016 TOKOPEDIA. All rights reserved.
//

#ifndef AnalyticsString_h
#define AnalyticsString_h

#pragma mark - Event
#define GA_EVENT_CLICK_CATEGORY @"clickKategori"
#define GA_EVENT_CLICK_INTERMEDIARY @"clickIntermediary"

#pragma mark - Event Category
#define GA_EVENT_CATEGORY_HOMEPAGE @"Homepage"
#define GA_EVENT_CATEGORY_SEARCH @"Search"
#define GA_EVENT_CATEGORY_SEARCH_RESULT @"Search Result"
#define GA_EVENT_CATEGORY_NO_SEARCH_RESULT @"No Search Result"
#define GA_EVENT_CATEGORY_SORT @"Sort"
#define GA_EVENT_CATEGORY_FILTER @"Filter"
#define GA_EVENT_CATEGORY_HOTLIST @"Hotlist"
#define GA_EVENT_CATEGORY_WISHLIST @"Wishlist"
#define GA_EVENT_CATEGORY_FEED @"Feed"
#define GA_EVENT_CATEGORY_RECENTLY_VIEWED @"Recently Viewed"
#define GA_EVENT_CATEGORY_FAVORITE @"Favorite"
#define GA_EVENT_CATEGORY_SNAP_SEARCH @"Snap Search"
#define GA_EVENT_CATEGORY_PRODUCT_DETAIL_PAGE @"Product Detail Page"
#define GA_EVENT_CATEGORY_INBOX_MESSAGE @"Message"
#define GA_EVENT_CATEGORY_INBOX_TALK @"Product Discussion"
#define GA_EVENT_CATEGORY_INBOX_REVIEW @"Review"
#define GA_EVENT_CATEGORY_INBOX_TICKET @"Help"
#define GA_EVENT_CATEGORY_INBOX_RESOLUTION @"Resolution"
#define GA_EVENT_CATEGORY_ATC @"Add to Cart"
#define GA_EVENT_CATEGORY_CHECKOUT @"Checkout"
#define GA_EVENT_CATEGORY_PAYMENT @"Payment"
#define GA_EVENT_CATEGORY_SALES @"Sales"
#define GA_EVENT_CATEGORY_NEW_ORDER @"New Order"
#define GA_EVENT_CATEGORY_SHIPPING @"Shipping"
#define GA_EVENT_CATEGORY_ORDER_STATUS @"Status"
#define GA_EVENT_CATEGORY_TRANSACTION @"Transaction"
#define GA_EVENT_CATEGORY_RECEIVED @"Received"
#define GA_EVENT_CATEGORY_SHOP_HOME @"Shop Home"
#define GA_EVENT_CATEGORY_SHOP_SETTINGS @"Manage Shop"
#define GA_EVENT_CATEGORY_SHOP_INFO @"Shop Info"
#define GA_EVENT_CATEGORY_ETALASE @"Etalase"
#define GA_EVENT_CATEGORY_SHOP_PRODUCT @"Product"
#define GA_EVENT_CATEGORY_SHOP_LOCATION @"Location"
#define GA_EVENT_CATEGORY_SHOP_SHIPPING @"Shipping"
#define GA_EVENT_CATEGORY_SHOP_NOTES @"Notes"
#define GA_EVENT_CATEGORY_CREATE_SHOP @"Create Shop"
#define GA_EVENT_CATEGORY_TAB_BAR @"Tab Bar"
#define GA_EVENT_CATEGORY_NOTIFICATION @"Toped Icon"
#define GA_EVENT_CATEGORY_REGISTER @"Register"
#define GA_EVENT_CATEGORY_LOGIN @"Login"
#define GA_EVENT_CATEGORY_CARDIO_SCAN @"Card IO Scan"
#define GA_EVENT_CATEGORY_FORGOT_PASSWORD @"Forgot Password"
#define GA_EVENT_CATEGORY_SECURITY_QUESTION @"Security Question"
#define GA_EVENT_CATEGORY_CREATE_SHOP @"Create Shop"
#define GA_EVENT_CATEGORY_SEARCH_RESULT @"Search Result"
#define GA_EVENT_CATEGORY_SHOP_HOME @"Shop Home"
#define GA_EVENT_CATEGORY_MANAGE_SHOP @"Manage Shop"
#define GA_EVENT_CATEGORY_SALES @"Sales"
#define GA_EVENT_CATEGORY_REPLACEMENT @"Peluang"
#define GA_EVENT_CATEGORY_NEW_ORDER @"New Order"
#define GA_EVENT_CATEGORY_SHIPMENT_CONFIRMATION @"Shipping"
#define GA_EVENT_CATEGORY_SHIPMENT_STATUS @"Status"
#define GA_EVENT_CATEGORY_TRANSACTION_LIST @"Transaction"
#define GA_EVENT_CATEGORY_RECEIVED @"Received"
#define GA_EVENT_CATEGORY_TRACKING @"Tracking"
#define GA_EVENT_CATEGORY_PULSA @"Pulsa"
#define GA_EVENT_KATEGORI @"Kategori"
#define GA_EVENT_CATEGORY_PAGE @"Category Page"
#define GA_EVENT_INTERMEDIARY_PAGE @"IntermediaryPage"
#define GA_EVENT_CATEGORY_QUICK_ACTION @"Quick Action"
#define GA_EVENT_CATEGORY_VERIFY_PHONE_NUMBER @"Verify Phone Number"
#define GA_EVENT_CATEGORY_ADD_PRODUCT @"Add Product"
#define GA_EVENT_CATEGORY_CHANGE_PHONE_NUMBER @"Change Phone Number"
#define GA_EVENT_CATEGORY_RECHARGE @"Recharge"
#define GA_EVENT_CATEGORY_SCREENSHOT @"Screenshot"
#define GA_EVENT_CATEGORY_REORDER @"Reorder"
#define GA_EVENT_CATEGORY_CREATE_SHOP @"Create Shop"
#define GA_EVENT_CATEGORY_FORCE_UPDATE_ALERT @"Force Update Alert"
#define GA_EVENT_CATEGORY_SETUP_TOUCHID @"Set Up Touch ID"
#define GA_EVENT_CATEGORY_ACTIVATION @"Activation"
#define GA_EVENT_CATEGORY_REPLACEMENT @"Peluang Filter"

#pragma mark - Event Action
#define GA_EVENT_ACTION_CLICK @"Click"
#define GA_EVENT_ACTION_VIEW @"View"
#define GA_EVENT_ACTION_SEND @"Send"
#define GA_EVENT_ACTION_ERROR @"Error"
#define GA_EVENT_ACTION_ABANDON @"Abandon"
#define GA_EVENT_ACTION_EDIT @"Edit"
#define GA_EVENT_ACTION_COPY @"Copy"
#define GA_EVENT_ACTION_SUCCESS @"Success"
#define GA_EVENT_ACTION_REGISTER_SUCCESS @"Register Success"
#define GA_EVENT_ACTION_REGISTER_ERROR @"Register Error"
#define GA_EVENT_ACTION_LOGIN_SUCCESS @"Login Success"
#define GA_EVENT_ACTION_LOGIN_ERROR @"Login Error"
#define GA_EVENT_ACTION_OTP_VERIFY @"OTP Verify"
#define GA_EVENT_ACTION_OTP_ON_CALL @"OTP On Call"
#define GA_EVENT_ACTION_OTP_SMS @"OTP SMS"
#define GA_EVENT_ACTION_CLICK_PRODUCT @"Click Product"
#define GA_EVENT_ACTION_CATEGORY @"Category"
#define GA_EVENT_ACTION_CATEGORY_BREAKDOWN @"Category Breakdown"
#define GA_EVENT_ACTION_NAVIGATION_SORT @"Bottom Navigation - Sort"
#define GA_EVENT_ACTION_NAVIGATION_FILTER @"Bottom Navigation - Filter"
#define GA_EVENT_ACTION_NAVIGATION_DISPLAY @"Bottom Navigation - Display"
#define GA_EVENT_ACTION_NAVIGATION_CATEGORY @"Bottom Navigation - Category"
#define GA_EVENT_ACTION_NAVIGATION_SHARE @"Bottom Navigation - Share"
#define GA_EVENT_ACTION_REQUEST_SUCCESS @"Request Success"
#define GA_EVENT_ACTION_REQUEST_FAILED @"Request Failed"
#define GA_EVENT_ACTION_VERIFY_SUCCESS @"Verify Success"
#define GA_EVENT_ACTION_VERIFY_FAILED @"Verify Failed"
#define GA_EVENT_ACTION_HOTLIST @"Hotlist"

#endif /* AnalyticsString_h */
