//
//  NotificationState.h
//  Tokopedia
//
//  Created by Tokopedia on 1/12/15.
//  Copyright (c) 2015 TOKOPEDIA. All rights reserved.
//

#ifndef Tokopedia_NotificationState_h
#define Tokopedia_NotificationState_h

#define STATE_NEW_MESSAGE 101
#define STATE_NEW_TALK 102

#define STATE_NEW_REVIEW 103
#define STATE_EDIT_REVIEW 113
#define STATE_REPLY_REVIEW 123

#define STATE_NEW_REPSYS 202
#define STATE_EDIT_REPSYS 212

#define STATE_NEW_ORDER 401
#define STATE_PURCHASE_REJECTED 304
#define STATE_PURCHASE_PROCESS_PARTIAL 303
#define STATE_CONFIRM_PACKAGE_RECEIVED 305

#define STATE_NEW_RESOLUTION 306
#define STATE_RESCENTER_SELLER_REPLY 115
#define STATE_RESCENTER_BUYER_REPLY  125
#define STATE_RESCENTER_SELLER_AGREE 135
#define STATE_RESCENTER_BUYER_AGREE  145
#define STATE_RESCENTER_ADMIN_SELLER_REPLY 155
#define STATE_RESCENTER_ADMIN_BUYER_REPLY  165
#define STATE_EDIT_RESOLUTION 115

#define IS_NOT_LOGIN @"0"

//GCM_MESSAGE         => 101,
//GCM_TALK            => 102,
//GCM_REVIEW          => 103,
//GCM_REVIEW_EDIT     => 113,
//GCM_REVIEW_REPLY    => 123,
//GCM_CONTACT         => 104,
//GCM_RC              => 105,
//GCM_NEWORDER        => 401,
//GCM_DRAWER_UPDATE   => 501,
//GCM_NOTIF_UPDATE    => 502,
//GCM_PEOPLE_PROFILE  => 601,
//GCM_PEOPLE_NOTIF_SETTING    => 602,
//GCM_PEOPLE_PRIVACY_SETTING  => 603,
//GCM_PEOPLE_ADDRESS_SETTING  => 604,
//GCM_SHOP_INFO       => 701,
//GCM_SHOP_PAYMENT    => 702,
//GCM_SHOP_ETALASE    => 703,
//GCM_SHOP_NOTES      => 704,
//GCM_PRODUCT_LIST    => 801



#endif
