--- 
excluded: 
  - Carthage
  - Pods
  - Tokopedia/API.swift
force_cast: warning
force_try: warning
force_unwrapping: warning
included: 
  - Tokopedia
whitelist_rules: 
  - force_unwrapping
  - force_try
  - force_cast
  - private_outlet
  - weak_delegate
  - void_return
  - vertical_whitespace
  - notification_center_detachment
  - multiple_closures_with_trailing_closure
  - conditional_returns_on_newline
  - control_statement
  - overridden_super_call
  - syntactic_sugar
  - prohibited_super_call
