included: # paths to include during linting. `--path` is ignored if present.
  - Tokopedia
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Tokopedia/API.swift
 
whitelist_rules:
  - force_try
  - force_cast
  - private_outlet
  - weak_delegate
  - void_return
  - vertical_whitespace
  - notification_center_detachment
  - multiple_closures_with_trailing_closure
  - conditional_returns_on_newline
  - control_statement
  - overridden_super_call
  - syntactic_sugar
  - prohibited_super_call
  

force_cast: warning
force_try: warning
