--- 
excluded: 
  - Carthage
  - Pods
  - Tokopedia/API.swift
force_cast: warning
force_try: 
  severity: error
force_unwrapping: warning
array_init:
  severity: error
block_based_kvo:
  severity: error
class_delegate_protocol:
  severity: error
compiler_protocol_init:
  severity: error
contains_over_first_not_nil:
  severity: error
discarded_notification_center_observer:
  severity: error
discouraged_direct_init:
  severity: error
explicit_acl:
  severity: error
explicit_init:
  severity: error
fatal_error_message:
  severity: error
first_where:
  severity: error
for_where:
  severity: error
generic_type_name:
  severity: error
identifier_name:
  severity: warning
implicitly_unwrapped_optional:
  severity: warning
  mode: all_except_iboutlets
is_disjoint:
  severity: error
joined_default_parameter:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_nsgeometry_functions:
  severity: error
nesting:
  type_level: 
    error: 2
  statement_level:
    error: 4
notification_center_detachment: error
object_literal: 
  severity: error
overridden_super_call:
  severity: error
override_in_extension:
  severity: warning
pattern_matching_keywords:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: warning
private_over_fileprivate:
  severity: error
prohibited_super_call:
  severity: error
redundant_nil_coalescing:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
sorted_first_last:
  severity: error
sorted_imports:
  severity: error
syntactic_sugar:
  severity: error
todo:
  severity: warning
trailing_semicolon:
  severity: error
type_name:
  severity: error
unneeded_break_in_switch:
  severity: error
unused_enumerated:
  severity: error
valid_ibinspectable:
  severity: error
weak_delegate:
  severity: error
yoda_condition:
  severity: error
custom_rules:
  migrate_masonry_to_snapkit:
    name: "Migrate Masonry to Snapkit"
    regex: "(mas_)"
    message: "Please use Snapkit instead of Masonry"
    severity: error
  literal_from_hex_string:
    name: "UIColor.fromHexString"
    regex: 'UIColor\s*\.fromHexString\s*\(\s*\".*\"\s*\)'
    severity: error
    message: 'Use #colorLiteral instead of UIColor.fromHexString()'
    
included: 
  - Tokopedia
  
whitelist_rules: 
  - custom_rules
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - compiler_protocol_init
  - contains_over_first_not_nil
  - discarded_notification_center_observer
  - discouraged_direct_init
  - explicit_acl
  - explicit_init
  - fatal_error_message
  - first_where
  - for_where
  - force_unwrapping
  - force_try
  - force_cast
  - generic_type_name
  - identifier_name
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - nesting
  - notification_center_detachment
  - object_literal
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - sorted_first_last
  - sorted_imports
  - todo
  - trailing_semicolon
  - type_name
  - unneeded_break_in_switch
  - unused_enumerated
  - weak_delegate
  - valid_ibinspectable
  - void_return
  - vertical_whitespace
  - multiple_closures_with_trailing_closure
  - control_statement
  - overridden_super_call
  - override_in_extension
  - syntactic_sugar
  - prohibited_super_call
  - yoda_condition
