# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

plugin 'cocoapods-static-frameworks'

use_frameworks!
static_frameworks

inhibit_all_warnings!

project 'Tokopedia', 'Debug-Optimized' => :debug

$DEBUG_CONFIGS = ['Debug', 'Debug-Optimized']

def react_pods
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'RCTText',
        'RCTWebSocket',
        'RCTNetwork',
        'DevSupport',
        'RCTAdSupport',
        'RCTVibration',
        'RCTImage',
        'RCTGeolocation',
        'RCTAnimation',
        'RCTActionSheet',
        'RCTSettings',
        'RCTLinkingIOS',
        'BatchedBridge',
        'RCTCameraRoll'
    ]
    
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'native-navigation', :path => '../node_modules/native-navigation'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'CodePush', :path => '../node_modules/react-native-code-push'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNSVG', :path => '../node_modules/react-native-svg'
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    pod 'Interactable', :path => '../node_modules/react-native-interactable'
end

def common_pods
    # Tweaks is installed manually, the use_frameworks! makes the Tweaks options not showing.
    
    pod 'APAddressBook/Swift', '~> 0.2.3'
    pod 'BlocksKit', '~> 2.2.5'
    pod 'ComponentKit', '~> 0.14'
    pod 'DTTJailbreakDetection', '~> 0.4.0'
    pod 'FLEX', :git => 'https://github.com/Flipboard/FLEX.git', :commit => '99eccdf4c34af9b1042d96313ad9cf12dd30ff1f', :configurations => $DEBUG_CONFIGS
    pod 'JLPermissions/Notification', '2.2.8'
    pod 'JLPermissions/Contacts', '2.2.8'
    pod 'JLPermissions/Location', '2.2.8'
    pod 'JLRoutes', '~> 1.6.2'
    pod 'Masonry', '~> 1.0.1'
    pod 'RestKit',  '~> 0.27.0'
    pod 'SPTPersistentCache', :git => 'https://github.com/spotify/SPTPersistentCache.git', :branch => 'master'
    pod 'youtube-ios-player-helper', '~> 0.1.6'
    pod 'SwiftLint', '~> 0.22.0'
    
    #Custom View Component
    pod 'AHKActionSheet', '~>0.5.4'
    pod 'BEMCheckBox' , '~>1.2.0'
    pod 'DownPicker', '~> 0.1.34'
    pod 'EAIntroView', '~> 2.8.0'
    pod 'EZYGradientView-ObjC', '~> 1.3'
    pod 'HMSegmentedControl', :git => 'https://github.com/billionssg/HMSegmentedControl'
    pod 'JDStatusBarNotification', '~> 1.5.5'
    pod 'KMNavigationBarTransition', '~> 1.1.5'
    pod 'MMNumberKeyboard', '~> 0.1.5'
    pod 'MXSegmentedPager', '~> 3.2.0'
    pod 'NJKWebViewProgress',  '~> 0.2.3'
    pod 'NSAttributedString-DDHTML', '1.2.0'
    pod 'OAStackView', '~> 1.0.1'
    pod 'Popover', :git => 'https://github.com/corin8823/Popover.git', :branch => 'master'
    pod 'RATreeView', '~> 2.1.2'
    pod 'RichEditorView', '~> 4.0.0'
    pod 'TPKeyboardAvoiding', '~> 1.3.1'
    pod 'TTTAttributedLabel',  '~> 1.13.4'
    pod 'UIAlertController+Blocks', '~> 0.9'
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
    pod 'VMaskTextField', '~>1.0.8'
    
    #Analytics
    pod 'Fabric', '~> 1.7.0'
    pod 'Crashlytics', '~> 3.9.0'
    pod 'AppsFlyerFramework',  '~> 4.5.1'
    pod 'Appsee', '~> 2.2'
    pod 'MoEngage-iOS-SDK', '~> 3.3.0'
    pod 'LogEntries', '~> 0.0.1'
    
    #Facebook Pod
    pod 'FBSDKCoreKit', '~>4.19.0'
    pod 'FBSDKLoginKit', '~>4.19.0'
    pod 'FBSDKShareKit', '~>4.19.0'
    
    #Google Pod
    pod 'GoogleSignIn', '~> 3.0.0'
    pod 'GoogleTagManager',  '~> 3.15.2'
    pod 'GoogleMaps',  '~> 2.1.1'
    pod 'GooglePlaces', '~> 2.1.1'
    pod 'FirebaseRemoteConfig', '~> 2.0.2'

    #Swift 3.0 pods
    pod 'RSKGrowingTextView', '~> 2.0'
    pod 'RSKPlaceholderTextView', '~> 2.0'
    pod 'SwiftOverlays', '~> 3.0.0'
    pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Xcode9-Swift3_2'
    pod 'RxSwift', '~> 3.3.1'
    pod 'RxCocoa', '~> 3.3.1'
    pod 'NSObject+Rx', '~>2.0.0'
    pod 'DKImagePickerController', '~> 3.5.0'
    pod 'RestKit/Testing', '~> 0.27.0'
    pod 'SnapKit', '~> 3.2.0'
    pod 'KeychainAccess', '~> 3.0'
    
    pod 'lottie-ios', '~> 1.5.2'
    pod 'Apollo', '~> 0.6.5'
    pod 'CFAlertViewController', '~> 2.3.1'
    pod 'Wrap'
    pod 'RxDataSources', '~> 1.0'
    
    #will be changed to proper version later
    pod 'Render', :git => 'https://github.com/esam091/Render.git', :branch => 'change-namespace'
    pod 'ReSwift', '~> 3.0.0'
    
    # networking and object mapping
    pod 'Moya/RxSwift', '~> 8.0.3'
    pod 'Unbox', '~> 2.4'
    pod 'MoyaUnbox/RxSwift', '~> 1.0.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    #Referrals
    pod "Branch", '0.18.8'
end

target "Tokopedia" do
    common_pods
    react_pods
    pod 'Reveal-iOS-SDK', :configurations => $DEBUG_CONFIGS
end

target "TokopediaTests" do
    react_pods
    common_pods
end

target "ServiceExtension" do
    platform :ios, "8.0"
    pod 'MORichNotification', '~> 1.1.1'
end

post_install do |installer|

    # https://github.com/CocoaPods/CocoaPods/issues/7003#issuecomment-329677763
    installer.aggregate_targets.each do |target|
        copy_pods_resources_path = "Pods/Target Support Files/#{target.name}/#{target.name}-resources.sh"
        string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
        assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'
        text = File.read(copy_pods_resources_path)
        new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
        File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
    end
    
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''

            if config.name == 'Release'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            elsif config.name == 'Debug-Optimized'
                config.build_settings['SWIFT_WHOLE_MODULE_OPTIMIZATION'] = 'YES'
            end

            if target.name == "MoEngage-iOS-SDK"
                config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
            end
        end
    end
    
    # prevent automatic c++ headers inclusion in Objective-C files which causes compile errors
    clear_component_kit_umbrella_header
end

def clear_component_kit_umbrella_header
    file = File.open('./Pods/Target Support Files/ComponentKit/ComponentKit-umbrella.h', 'w')
    file.close
end
