//
//  detail.h
//  Tokopedia
//
//  Created by IT Tkpd on 9/8/14.
//  Copyright (c) 2014 TOKOPEDIA. All rights reserved.
//

#ifndef Tokopedia_detail_h
#define Tokopedia_detail_h

#define kTKPDDETAIL_APISTATUSKEY @"status"
#define kTKPRDETAIL_APISERVERPROCESSTIMEKEY @"server_process_time"
#define kTKPDDETAIL_APIRESULTKEY @"result"

#define kTKPDDETAILPRODUCT_APIINFOKEY @"info"
#define kTKPDDETAILPRODUCT_APIPRODUCTWEIGHTUNITKEY @"product_weight_unit"
#define kTKPDDETAILPRODUCT_APIPRODUCTDESCRIPTIONKEY @"product_description"
#define kTKPDDETAILPRODUCT_APIPRODUCTPRICEKEY @"product_price"
#define kTKPDDETAILPRODUCT_APIPRODUCTINSURANCEKEY @"product_insurance"
#define kTKPDDETAILPRODUCT_APIPRODUCTCONDITIONKEY @"product_condition"
#define kTKPDDETAILPRODUCT_APIPRODUCTMINORDERKEY @"product_min_order"
#define kTKPDDETAILPRODUCT_APIPRODUCTSTATUSKEY @"product_status"
#define kTKPDDETAILPRODUCT_APIPRODUCTLASTUPDATEKEY @"product_last_update"
#define kTKPDDETAILPRODUCT_APIPRODUCTIDKEY @"product_id"
#define kTKPDDETAILPRODUCT_APIPRODUCTPRICEALERTKEY @"product_price_alert"
#define kTKPDDETAILPRODUCT_APIPRODUCTNAMEKEY @"product_name"

#define kTKPDDETAILPRODUCT_APISTATISTICKEY @"statistic"
#define kTKPDDETAILPRODUCT_APIPRODUCTSOLDKEY @"product_sold"
#define kTKPDDETAILPRODUCT_APIPRODUCTTRANSACTIONKEY @"product_transaction"
#define kTKPDDETAILPRODUCT_APIPRODUCTSUCCESSRATEKEY @"product_success_rate"
#define kTKPDDETAILPRODUCT_APIPRODUCTVIEWKEY @"product_view"
#define kTKPDDETAILPRODUCT_APIPRODUCTRATINGKEY @"product_rating"
#define kTKPDDETAILPRODUCT_APIPRODUCTCANCELRATEKEY @"product_cancel_rate"
#define kTKPDDETAILPRODUCT_APIPRODUCTTALKKEY @"product_talk"
#define kTKPDDETAILPRODUCT_APIPRODUCTREVIEWKEY @"product_review"

#define kTKPDDETAILPRODUCT_APISHOPINFOKEY @"shop_info"
#define kTKPDDETAILPRODUCT_APISHOPOPENSINCEKEY @"shop_open_since"
#define kTKPDDETAILPRODUCT_APISHOPLOCATIONKEY @"shop_location"
#define kTKPDDETAILPRODUCT_APISHOPIDKEY @"shop_id"
#define kTKPDDETAILPRODUCT_APISHOPLASTLOGINKEY @"shop_owner_last_login"
#define kTKPDDETAILPRODUCT_APISHOPTAGLINEKEY @"shop_tagline"
#define kTKPDDETAILPRODUCT_APISHOPNAMEKEY @"shop_name"
#define kTKPDDETAILPRODUCT_APISHOPSTATSKEY @"shop_stats"
#define kTKPDDETAILPRODUCT_APISHOPISFAVKEY @"shop_already_favorited"
#define kTKPDDETAILPRODUCT_APISHOPDESCRIPTIONKEY @"shop_description"
#define kTKPDDETAILPRODUCT_APISHOPAVATARKEY @"shop_avatar"
#define kTKPDDETAILPRODUCT_APISHOPDOMAINKEY @"shop_domain"

#define kTKPDDETAILPRODUCT_APISHOPSTATKEY @"shop_stats"
#define kTKPDDETAILPRODUCT_APISHOPSERVICERATEKEY @"shop_service_rate"
#define kTKPDDETAILPRODUCT_APISHOPSERVICEDESCRIPTIONKEY @"shop_service_description"
#define kTKPDDETAILPRODUCT_APISHOPSPEEDRATEKEY @"shop_speed_rate"
#define kTKPDDETAILPRODUCT_APISHOPACURACYRATEKEY @"shop_accuracy_rate"
#define kTKPDDETAILPRODUCT_APISHOPACURACYDESCRIPTIONKEY @"shop_accuracy_description"
#define kTKPDDETAILPRODUCT_APISHOPSPEEDDESCRIPTIONKEY @"shop_speed_description"

#define kTKPDDETAILPRODUCT_APIBREADCRUMBKEY @"breadcrumb"
#define kTKPDDETAILPRODUCT_APIDEPARTMENTNAMEKEY @"department_name"
#define kTKPDDETAILPRODUCT_APIDEPARTMENTIDKEY @"department_id"


#define kTKPDDETAILPRODUCT_APIPRODUCTIMAGEKEY @"product_image"

#define kTKPDDETAILPRODUCT_APIPRODUCTIMAGESKEY @"product_images"
#define kTKPDDETAILPRODUCT_APIIMAGEIDKEY @"image_id"
#define kTKPDDETAILPRODUCT_APIIMAGESTATUSKEY @"image_status"
#define kTKPDDETAILPRODUCT_APIIMAGEDESCRIPTIONKEY @"image_description"
#define kTKPDDETAILPRODUCT_APIIMAGEPRIMARYKEY @"image_primary"
#define kTKPDDETAILPRODUCT_APIIMAGESRCKEY @"image_src"

///SHOP//

#define kTKPDDETAILSHOP_APICLOSEDINFOKEY @"closed_info"
#define kTKPDDETAILSHOP_APIUNTILKEY @"until"
#define kTKPDDETAILSHOP_APIRESONKEY @"reason"

#define kTKPDDETAILSHOP_APIOWNERKEY @"owner"
#define kTKPDDETAILSHOP_APIOWNERIMAGEKEY @"owner_image"
#define kTKPDDETAILSHOP_APIOWNERPHONEKEY @"owner_phone"
#define kTKPDDETAILSHOP_APIOWNERIDKEY @"owner_id"
#define kTKPDDETAILSHOP_APIOWNEREMAILKEY @"owner_email"
#define kTKPDDETAILSHOP_APIOWNERNAMEKEY @"owner_name"
#define kTKPDDETAILSHOP_APIOWNERMESSAGERKEY @"owner_messager"

#define kTKPDDETAILSHOP_APIINFOKEY @"info"
#define kTKPDDETAILSHOP_APICOVERKEY @"shop_cover"
#define kTKPDDETAILSHOP_APITOTALFAVKEY @"shop_total_favorit"

#define kTKPDDETAILSHOP_APISTATKEY @"stats"
#define kTKPDDETAILSHOP_APISHIPMENTKEY @"shipment"
#define kTKPDDETAILSHOP_APISHIPMENTIDKEY @"shipment_id"
#define kTKPDDETAILSHOP_APISHIPMENTPACKAGEKEY @"shipment_package"

#define kTKPDDETAILSHOP_APISHIPPINGIDKEY @"shipping_id"
#define kTKPDDETAILSHOP_APIPRODUCTNAMEKEY @"product_name"

#define kTKPDDETAILSHOP_APISHIPMENTIMAGEKEY @"shipment_image"
#define kTKPDDETAILSHOP_APISHIPMENTNAMEKEY @"shipment_name"

#define kTKPDDETAILSHOP_APIPAYMENTKEY @"payment"
#define kTKPDDETAILSHOP_APIPAYMENTIMAGEKEY @"payment_image"
#define kTKPDDETAILSHOP_APIPAYMENTNAMEKEY @"payment_name"

#define kTKPDDETAILSHOP_APIADDRESSKEY @"address"
#define kTKPDDETAILSHOP_APIADDRESSNAMEKEY @"address_name"
#define kTKPDDETAILSHOP_APIADDRESSIDKEY @"address_id"
#define kTKPDDETAILSHOP_APIADDRESSPOSTALKEY @"address_postal"
#define kTKPDDETAILSHOP_APIADDRESSDISTRICTKEY @"address_district"
#define kTKPDDETAILSHOP_APIADDRESSFAXKEY @"address_fax"
#define kTKPDDETAILSHOP_APIADDRESSCITYKEY @"address_city"
#define kTKPDDETAILSHOP_APIADDRESSPHONEKEY @"address_phone"
#define kTKPDDETAILSHOP_APIADDRESSEMAILKEY @"address_email"
#define kTKPDDETAILSHOP_APIADDRESSPROVINCEKEY @"address_province"

#define kTKPDDETAILPRODUCT_APIPATH @"product.pl"
#define kTKPDDETAILSHOP_APIPATH @"shop.pl"

#endif
