//
//  detail.h
//  Tokopedia
//
//  Created by IT Tkpd on 9/8/14.
//  Copyright (c) 2014 TOKOPEDIA. All rights reserved.
//

#ifndef Tokopedia_detail_h
#define Tokopedia_detail_h

#define kTKPDTITLE_TALK @"Talk About It"
#define kTKPDTITLE_REVIEW @"Review"
#define kTKPDTITLE_SHOP_NOTES @"Shop Note"
#define kTKPDTITLE_SHOP_INFO @"Shop Information"
#define KTKPDTITLE_FAV_THIS_SHOP @"People who Favorited This Shop"

#define kTKPDDETAIL_DATASHOPSKEY @"shop"
#define kTKPDDETAIL_DATAINFOSHOPSKEY @"infoshop"
#define kTKPDDETAIL_DATALOCATIONARRAYKEY @"locationarray"
#define kTKPDDETAIL_DATAQUERYKEY @"query"
#define kTKPDDETAIL_DATAETALASEKEY @"etalase"
#define kTKPDDETAIL_DATAINDEXKEY @"index"
#define kTKPDDETAIL_DATAINDEXPATHKEY @"indexpath"
#define kTKPDDETAILETALASE_DATAINDEXPATHKEY @"etalaseindexpath"
#define kTKPDDETAIL_DATACOLUMNKEY @"column"

#define kTKPDDETAIL_APILISTKEYPATH @"result.list"
#define kTKPDDETAIL_APIPAGINGKEYPATH @"result.paging"
#define kTKPDDETAIL_APIRESULTKEY @"result"

#define kTKPDDETAIL_APIACTIONKEY @"action"
#define kTKPDDETAIL_APIPRODUCTIDKEY @"product_id"
#define kTKPDDETAIL_APICATALOGIDKEY @"catalog_id"
#define kTKPDDETAIL_APISHOPIDKEY @"shop_id"

#pragma mark - Get Action
#define kTKPDDETAIL_APIGETDETAILACTIONKEY @"get_detail"
#define kTKPDDETAIL_APIGETPRODUCTREVIEWKEY @"get_product_review"
#define kTKPDDETAIL_APIGETPRODUCTTALKKEY @"get_product_talk"
#define kTKPDDETAIL_APIGETCOMMENTBYTALKID @"get_comment_by_talk_id"
#define kTKPDDETAIL_APIGETCATALOGDETAILKEY @"get_catalog_detail"
#define kTKPDDETAIL_APIGETSHOPDETAILKEY @"get_shop_info"
#define kTKPDDETAIL_APIGETSHOPPRODUCTKEY @"get_shop_product"
#define kTKPDDETAIL_APIGETSHOPTALKKEY @"get_shop_talk"
#define kTKPDDETAIL_APIGETSHOPREVIEWKEY @"get_shop_review"
#define kTKPDDETAIL_APIGETSHOPNOTESKEY @"get_shop_notes"
#define kTKPDDETAIL_APIGETNOTESDETAILKEY @"get_notes_detail"
#define kTKPDDETAIL_APIGETETALASEKEY @"get_shop_etalase"
#define kTKPDDETAIL_APIGETSHOPFAVORITEDKEY @"get_people_who_favorite_myshop"

#define kTKPDDETAIL_APIPAGEKEY @"page"
#define kTKPDDETAIL_APITOTALPAGEKEY @"total_page"
#define kTKPDDETAIL_APILIMITKEY @"per_page"
#define kTKPDDETAIL_APILOCATIONKEY @"location"
#define kTKPDDETAIL_APICONDITIONKEY @"condition"
#define kTKPDDETAIL_APIORERBYKEY @"order_by"
#define kTKPDDETAIL_APISORTKEY @"sort"
#define kTKPDDETAIL_APIKEYWORDKEY @"keyword"
#define kTKPDDETAIL_APIETALASEIDKEY @"menu_id"

#define kTKPDDETAILREVIEW_LIMITPAGE 5
#define kTKPDSHOPPRODUCT_LIMITPAGE 6

#define kTKPDDETAIL_DATASHOPTITLEKEY @"Shop"

#define kTKPDDETAIL_APIQUERYKEY @"query"

#define kTKPDDETAILPRODUCT_APIINFOKEY @"info"
#define kTKPDDETAILPRODUCT_APIPRODUCTWEIGHTUNITKEY @"product_weight_unit"
#define kTKPDDETAILPRODUCT_APIPRODUCTDESCRIPTIONKEY @"product_description"
#define kTKPDDETAILPRODUCT_APIPRODUCTPRICEKEY @"product_price"
#define kTKPDDETAILPRODUCT_APIPRODUCTINSURANCEKEY @"product_insurance"
#define kTKPDDETAILPRODUCT_APIPRODUCTCONDITIONKEY @"product_condition"
#define kTKPDDETAILPRODUCT_APIPRODUCTMINORDERKEY @"product_min_order"
#define kTKPDDETAILPRODUCT_APIPRODUCTSTATUSKEY @"product_status"
#define kTKPDDETAILPRODUCT_APIPRODUCTLASTUPDATEKEY @"product_last_update"
#define kTKPDDETAILPRODUCT_APIPRODUCTIDKEY @"product_id"
#define kTKPDDETAILPRODUCT_APIPRODUCTPRICEALERTKEY @"product_price_alert"
#define kTKPDDETAILPRODUCT_APIPRODUCTNAMEKEY @"product_name"

#define kTKPDDETAILPRODUCT_APISTATISTICKEY @"statistic"
#define kTKPDDETAILPRODUCT_APIPRODUCTSOLDKEY @"product_sold"
#define kTKPDDETAILPRODUCT_APIPRODUCTTRANSACTIONKEY @"product_transaction"
#define kTKPDDETAILPRODUCT_APIPRODUCTSUCCESSRATEKEY @"product_success_rate"
#define kTKPDDETAILPRODUCT_APIPRODUCTVIEWKEY @"product_view"
#define kTKPDDETAILPRODUCT_APIPRODUCTRATINGKEY @"product_rating"
#define kTKPDDETAILPRODUCT_APIPRODUCTCANCELRATEKEY @"product_cancel_rate"
#define kTKPDDETAILPRODUCT_APIPRODUCTTALKKEY @"product_talk"
#define kTKPDDETAILPRODUCT_APIPRODUCTREVIEWKEY @"product_review"

#define kTKPDDETAILPRODUCT_APISHOPINFOKEY @"shop_info"
#define kTKPDDETAILPRODUCT_APISHOPOPENSINCEKEY @"shop_open_since"
#define kTKPDDETAILPRODUCT_APISHOPLOCATIONKEY @"shop_location"
#define kTKPDDETAILPRODUCT_APISHOPLASTLOGINKEY @"shop_owner_last_login"
#define kTKPDDETAILPRODUCT_APISHOPTAGLINEKEY @"shop_tagline"
#define kTKPDDETAILPRODUCT_APISHOPNAMEKEY @"shop_name"
#define kTKPDDETAILPRODUCT_APISHOPSTATSKEY @"shop_stats"
#define kTKPDDETAILPRODUCT_APISHOPISFAVKEY @"shop_already_favorited"
#define kTKPDDETAILPRODUCT_APISHOPDESCRIPTIONKEY @"shop_description"
#define kTKPDDETAILPRODUCT_APISHOPAVATARKEY @"shop_avatar"
#define kTKPDDETAILPRODUCT_APISHOPDOMAINKEY @"shop_domain"

#define kTKPDDETAILPRODUCT_APISHOPSTATKEY @"shop_stats"
#define kTKPDDETAILPRODUCT_APISHOPSERVICERATEKEY @"shop_service_rate"
#define kTKPDDETAILPRODUCT_APISHOPSERVICEDESCRIPTIONKEY @"shop_service_description"
#define kTKPDDETAILPRODUCT_APISHOPSPEEDRATEKEY @"shop_speed_rate"
#define kTKPDDETAILPRODUCT_APISHOPACURACYRATEKEY @"shop_accuracy_rate"
#define kTKPDDETAILPRODUCT_APISHOPACURACYDESCRIPTIONKEY @"shop_accuracy_description"
#define kTKPDDETAILPRODUCT_APISHOPSPEEDDESCRIPTIONKEY @"shop_speed_description"

#define kTKPDDETAILPRODUCT_APIBREADCRUMBKEY @"breadcrumb"
#define kTKPDDETAILPRODUCT_APIDEPARTMENTNAMEKEY @"department_name"
#define kTKPDDETAILPRODUCT_APIDEPARTMENTIDKEY @"department_id"

#define kTKPDDETAILPRODUCT_APIWHOLESALEMINKEY @"wholesale_min"
#define kTKPDDETAILPRODUCT_APIWHOLESALEPRICEKEY @"wholesale_price"
#define kTKPDDETAILPRODUCT_APIWHOLESALEMAXKEY @"wholesale_max"

#define kTKPDDETAILPRODUCT_APIPRODUCTIMAGEKEY @"product_image"

#define kTKPDDETAILPRODUCT_APIPRODUCTIMAGESKEY @"product_images"
#define kTKPDDETAILPRODUCT_APIIMAGEIDKEY @"image_id"
#define kTKPDDETAILPRODUCT_APIIMAGESTATUSKEY @"image_status"
#define kTKPDDETAILPRODUCT_APIIMAGEDESCRIPTIONKEY @"image_description"
#define kTKPDDETAILPRODUCT_APIIMAGEPRIMARYKEY @"image_primary"
#define kTKPDDETAILPRODUCT_APIIMAGESRCKEY @"image_src"

#define kTKPDDETAIL_APIWHOLESALEPRICEPATHKEY @"wholesale_price"
#define kTKPDDETAIL_APIBREADCRUMBPATHKEY @"breadcrumb"
#define kTKPDDETAIL_APIOTHERPRODUCTPATHKEY @"other_product"
#define kTKPDDETAIL_APIPRODUCTIMAGEPATHKEY @"product_images"
#define kTKPDDETAIL_APICATALOGIMAGEPATHKEY @"catalog_image"
#define kTKPDDETAIL_APIPRODUCTLISTPATHKEY @"product_list"
#define kTKPDDETAIL_APICATALOGSPECSPATHKEY @"catalog_specs"
#define kTKPDDETAIL_APICATALOGSPECCHILDSPATHKEY @"spec_childs"

#pragma mark - Shop

#define kTKPDDETAILSHOP_APICLOSEDINFOKEY @"closed_info"
#define kTKPDDETAILSHOP_APIUNTILKEY @"until"
#define kTKPDDETAILSHOP_APIRESONKEY @"reason"

#define kTKPDDETAILSHOP_APIOWNERKEY @"owner"
#define kTKPDDETAILSHOP_APIOWNERIMAGEKEY @"owner_image"
#define kTKPDDETAILSHOP_APIOWNERPHONEKEY @"owner_phone"
#define kTKPDDETAILSHOP_APIOWNERIDKEY @"owner_id"
#define kTKPDDETAILSHOP_APIOWNEREMAILKEY @"owner_email"
#define kTKPDDETAILSHOP_APIOWNERNAMEKEY @"owner_name"
#define kTKPDDETAILSHOP_APIOWNERMESSAGERKEY @"owner_messager"

#define kTKPDDETAILSHOP_APIINFOKEY @"info"
#define kTKPDDETAILSHOP_APICOVERKEY @"shop_cover"
#define kTKPDDETAILSHOP_APITOTALFAVKEY @"shop_total_favorit"

#define kTKPDDETAILSHOP_APISTATKEY @"stats"
#define kTKPDDETAILSHOP_APISHIPMENTKEY @"shipment"
#define kTKPDDETAILSHOP_APISHIPMENTIDKEY @"shipment_id"
#define kTKPDDETAILSHOP_APISHIPMENTPACKAGEKEY @"shipment_package"

#define kTKPDDETAILSHOP_APISHIPPINGIDKEY @"shipping_id"
#define kTKPDDETAILSHOP_APIPRODUCTNAMEKEY @"product_name"

#define kTKPDDETAILSHOP_APISHIPMENTIMAGEKEY @"shipment_image"
#define kTKPDDETAILSHOP_APISHIPMENTNAMEKEY @"shipment_name"

#define kTKPDDETAILSHOP_APIPAYMENTKEY @"payment"
#define kTKPDDETAILSHOP_APIPAYMENTIMAGEKEY @"payment_image"
#define kTKPDDETAILSHOP_APIPAYMENTNAMEKEY @"payment_name"

#define kTKPDDETAILSHOP_APIADDRESSKEY @"address"
#define kTKPDDETAILSHOP_APIADDRESSNAMEKEY @"address_name"
#define kTKPDDETAILSHOP_APIADDRESSIDKEY @"address_id"
#define kTKPDDETAILSHOP_APIADDRESSPOSTALKEY @"address_postal"
#define kTKPDDETAILSHOP_APIADDRESSDISTRICTKEY @"address_district"
#define kTKPDDETAILSHOP_APIADDRESSFAXKEY @"address_fax"
#define kTKPDDETAILSHOP_APIADDRESSCITYKEY @"address_city"
#define kTKPDDETAILSHOP_APIADDRESSPHONEKEY @"address_phone"
#define kTKPDDETAILSHOP_APIADDRESSEMAILKEY @"address_email"
#define kTKPDDETAILSHOP_APIADDRESSPROVINCEKEY @"address_province"

#define kTKPDSHOP_APISHOPTOTALTRANSACTIONKEY @"shop_total_transaction"
#define kTKPDSHOP_APISHOPTOTALETALASEKEY @"shop_total_etalase"
#define kTKPDSHOP_APISHOPTOTALPRODUCTKEY @"shop_total_product"
#define kTKPDSHOP_APISHOPTOTALSOLDKEY @"shop_item_sold"

#define kTKPDSHOP_APIETALASENAMEKEY @"etalase_name"
#define kTKPDSHOP_APIETALASEIDKEY @"etalase_id"
#define kTKPDSHOP_APIETALASETOTALPRODUCTKEY @"etalase_total_product"

#pragma mark - Review

#define kTKPDREVIEW_APIADVREVIEWKEY @"advance_review"

#define kTKPDREVIEW_APIRATINGLISTKEY @"rating_list"
#define kTKPDREVIEW_APINETRALQUALITYKEY @"netral_quality_point"
#define kTKPDREVIEW_APINEGATIVEACCURACYKEY @"negative_accuracy_point"
#define kTKPDREVIEW_APIRATINGACCURACYKEY @"rating_accuracy_point"
#define kTKPDREVIEW_APINEGATIVEQUALITYKEY @"negative_quality_point"
#define kTKPDREVIEW_APIPOSITIVEQUALITYKEY @"positive_quality_point"
#define kTKPDREVIEW_APINETRALACCURACYKEY @"netral_accuracy_point"
#define kTKPDREVIEW_APIPOSITIVEACCURACYKEY @"positive_accuracy_point"
#define kTKPDREVIEW_APITOTALREVIEWKEY @"total_review"
#define kTKPDREVIEW_APIRATINGQUALITYKEY @"rating_quality_point"

#define kTKPDREVIEW_APIRATINGSTARPOINTKEY @"rating_star_point"
#define kTKPDREVIEW_APIRATINGACCURACYKEY @"rating_accuracy_point"
#define kTKPDREVIEW_APIRATINGQUALITYKEY @"rating_quality_point"

#define kTKPDREVIEW_APIREVIEWRESPONSEKEY @"review_response"
#define kTKPDREVIEW_APIRESPONSECREATETIMEKEY @"response_create_time"
#define kTKPDREVIEW_APIRESPONSEMESSAGEKEY @"response_message"

#define kTKPDREVIEW_APIREVIEWSHOPIDKEY @"review_shop_id"
#define kTKPDREVIEW_APIREVIEWUSERIMAGEKEY @"review_user_image"
#define kTKPDREVIEW_APIREVIEWCREATETIMEKEY @"review_create_time"
#define kTKPDREVIEW_APIREVIEWIDKEY @"review_id"

#define kTKPDREVIEW_APIPRODUCTNAMEKEY @"review_product_name"
#define kTKPDREVIEW_APIPRODUCTIDKEY @"review_product_id"
#define kTKPDREVIEW_APIPRODUCTIMAGEKEY @"review_product_image"

#define kTKPDREVIEW_APIREVIEWPRODUCTOWNERKEY @"review_product_owner"
#define kTKPDREVIEW_APIUSERIDKEY @"user_id"
#define kTKPDREVIEW_APIUSERIMAGEKEY @"user_image"
#define kTKPDREVIEW_APIUSERNAME @"user_name"

#define kTKPDREVIEW_APIREVIEWUSERNAMEKEY @"review_user_name"
#define kTKPDREVIEW_APIREVIEWRATEQUALITY @"review_rate_quality"
#define kTKPDREVIEW_APIREVIEWRATESPEEDKEY @"review_rate_speed"
#define kTKPDREVIEW_APIREVIEWRATESERVICEKEY @"review_rate_service"
#define kTKPDREVIEW_APIREVIEWRATEACCURACYKEY @"review_rate_accuracy"
#define kTKPDREVIEW_APIREVIEWMESSAGEKEY @"review_message"
#define kTKPDREVIEW_APIREVIEWUSERIDKEY @"review_user_id"

#define kTKPDREVIEW_APIMONTHRANGEKEY @"month_range"
#define kTKPDREVIEW_APIRATEACCURACYKEY @"shop_accuracy"
#define kTKPDTEVIEW_APIRATEQUALITYKEY @"shop_quality"

#pragma mark - Talk
#define kTKPDTALK_APITALKTOTALCOMMENTKEY @"talk_total_comment"
#define kTKPDTALK_APITALKUSERIMAGEKEY @"talk_user_image"
#define kTKPDTALK_APITALKUSERNAMEKEY @"talk_user_name"
#define kTKPDTALK_APITALKIDKEY @"talk_id"
#define kTKPDTALK_APITALKCREATETIMEKEY @"talk_create_time"
#define kTKPDTALK_APITALKMESSAGEKEY @"talk_message"
#define kTKPDTALK_APITALKFOLLOWSTATUSKEY @"talk_follow_status"
#define kTKPDTALK_APITALKSHOPID @"talk_shop_id"


#define kTKPDTALK_APITALKPRODUCTNAMEKEY @"talk_product_name"
#define kTKPDTALK_APITALKPRODUCTIMAGEKEY @"talk_product_image"
#define kTKPDTALK_APITALKPRODUCTIDKEY @"talk_product_id"
#define kTKPDTALK_APITALKOWNKEY @"talk_own"
#define kTKPDTALK_APITALKUSERIDKEY @"talk_user_id"

#pragma mark - Talk Comment
#define kTKPDTALKCOMMENT_TALKID @"talk_id"
#define kTKPDTALKCOMMENT_MESSAGE @"comment_message"
#define kTKPDTALKCOMMENT_ID @"comment_id"
#define kTKPDTALKCOMMENT_ISMOD @"is_moderator"
#define kTKPDTALKCOMMENT_ISSELLER @"is_seller"
#define kTKPDTALKCOMMENT_CREATETIME @"create_time"
#define kTKPDTALKCOMMENT_USERIMAGE @"user_image"
#define kTKPDTALKCOMMENT_USERNAME @"user_name"

#pragma mark - Notes
#define kTKPDNOTES_APINOTEIDKEY @"note_id"
#define kTKPDNOTES_APINOTESIDKEY @"notes_id"
#define kTKPDNOTES_APINOTESSTATUSKEY @"notes_status"
#define kTKPDNOTES_APINOTESTITLEKEY @"notes_title"

#define kTKPDNOTE_APINOTESTITLEKEY @"notes_title"
#define kTKPDNOTE_APINOTESUPDATETIMEKEY @"notes_update_time"
#define kTKPDNOTE_APINOTESCONTENTKEY @"notes_content"

#pragma mark - Favorited
#define kTKPDFAVORITED_APIUSERIDKEY @"user_id"
#define kTKPDFAVORITED_APIUSERIMAGEKEY @"user_image"
#define kTKPDFAVORITED_APIUSERNAMEKEY @"user_name"

#pragma mark - Catalog
#define kTKPDDETAILCATALOG_APICATALOGINFOKEY @"catalog_info"
#define kTKPDDETAILCATALOG_APICATALOGSPECSKEY @"catalog_specs"
#define kTKPDDETAILCATALOG_APICATALOGREVIEWKEY @"catalog_review"
#define kTKPDDETAILCATALOG_APICATALOGMARKETPRICEKEY @"catalog_market_price"
#define kTKPDDETAILCATALOG_APICATALOGSHOPSKEY @"catalog_shops"
#define kTKPDDETAILCATALOG_APICATALOGIMAGEKEY @"catalog_image"

#define kTKPDDETAILCATALOG_APICATALOGDESCKEY @"catalog_description"
#define kTKPDDETAILCATALOG_APICATALOGKEYKEY @"catalog_key"
#define kTKPDDETAILCATALOG_APICATALOGDEPARTMENTIDKEY @"catalog_department_id"
#define kTKPDDETAILCATALOG_APICATALOGIDKEY @"catalog_id"
#define kTKPDDETAILCATALOG_APICATALOGNAMEKEY @"catalog_name"
#define kTKPDDETAILCATALOG_APICATALOGPRICEKEY @"catalog_price"
#define kTKPDDETAILCATALOG_APICATALOGIMAGESKEY @"catalog_image"

#define kTKPDDETAILCATALOG_APIIMAGEPRIMARYKEY @"image_primary"
#define kTKPDDETAILCATALOG_APIIMAGESRCKEY @"image_src"

#define kTKPDDETAILCATALOG_APIPRICEMINKEY @"price_min"
#define kTKPDDETAILCATALOG_APIPRICEMAXKEY @"price_max"

#define kTKPDDETAILCATALOG_APIREVIEWIMAGEKEY @"review_from_image"
#define kTKPDDETAILCATALOG_APIREVIEWRATINGKEY @"review_rating"
#define kTKPDDETAILCATALOG_APIREVIEWURLKEY @"review_url"
#define kTKPDDETAILCATALOG_APIREVIEWFROMURLKEY @"review_from_url"
#define kTKPDDETAILCATALOG_APIREVIEWFROMKEY @"review_from"
#define kTKPDDETAILCATALOG_APICATALOGIDKEY @"catalog_id"
#define kTKPDDETAILCATALOG_APIREVIEWDESCKEY @"review_description"

#define kTKPDDETAILCATALOG_APIMAXPRICEKEY @"max_price"
#define kTKPDDETAILCATALOG_APITIMEKEY @"time"
#define kTKPDDETAILCATALOG_APINAMEKEY @"name"
#define kTKPDDETAILCATALOG_APIMINPRICEKEY @"min_price"

#define kTKPDDETAIL_APILISTKEY @"list"
#define kTKPDDETAIL_APIPAGINGKEY @"paging"
#define kTKPDDETAIL_APIDETAILKEY @"detail"

#define kTKPDDETAILCATALOG_APIPRODUCTLISTKEY @"product_list"
#define kTKPDDETAILCATALOG_APISHOPRATEACCURACYKEY @"shop_rate_accuracy"
#define kTKPDDETAILCATALOG_APISHOPIMAGEKEY @"shop_image"
#define kTKPDDETAIL_APISHOPIDKEY @"shop_id"
#define kTKPDDETAILCATALOG_APISHOPLOCATIONKEY @"shop_location"
#define kTKPDDETAILCATALOG_APISHOPRATESPEEDKEY @"shop_rate_speed"
#define kTKPDDETAILCATALOG_APIISGOLDSHOPKEY @"is_gold_shop"
#define kTKPDDETAILCATALOG_APISHOPNAMEKEY @"shop_name"
#define kTKPDDETAILCATALOG_APISHOPTOTALADDRESSKEY @"shop_total_address"
#define kTKPDDETAILCATALOG_APISHOPTOTALPRODUCTKEY @"shop_total_product"
#define kTKPDDETAILCATALOG_APISHOPRATESERVICEKEY @"shop_rate_service"

#define kTKPDDETAILCATALOG_APIPRODUCTPRICEKEY @"product_price"
#define kTKPDDETAILCATALOG_APIPRODUCTIDKEY @"product_id"
#define kTKPDDETAILCATALOG_APIPRODUCTCONDITIONKEY @"product_condition"
#define kTKPDDETAILCATALOG_APIPRODUCTNAMEKEY @"product_name"

#define kTKPDDETAILCATALOG_APISPECSKEY @"catalog_specs"
#define kTKPDDETAILCATALOG_APISPECCHILDSKEY @"spec_childs"
#define kTKPDDETAILCATALOG_APISPECVALKEY @"spec_val"
#define kTKPDDETAILCATALOG_APISPECKEYKEY @"spec_key"
#define kTKPDDETAILCATALOG_APISPECHEADERKEY @"spec_header"

#define kTKPDDETAILCATALOG_APILOCATIONKEY @"catalog_location"
#define kTKPDDETAILCATALOG_APILOCATIONNAMEKEY @"location_name"
#define kTKPDDETAILCATALOG_APILOCATIONIDKEY @"location_id"
#define kTKPDDETAILCATALOG_APITOTALSHOPKEY @"total_shop"

#define kTKPDDETAIL_APIURINEXTKEY @"uri_next"

#define kTKPDDETAILPRODUCT_APIPATH @"product.pl"
#define kTKDPDETAILCATALOG_APIPATH @"catalog.pl"
#define kTKPDDETAILSHOP_APIPATH @"shop.pl"
#define kTKPDDETAILNOTES_APIPATH @"notes.pl"
#define kTKPDDETAILTALK_APIPATH @"talk.pl"

#define kTKPDDETAIL_STANDARDTABLEVIEWCELLIDENTIFIER @"cell"
#define kTKPDDETAIL_NODATACELLTITLE @"no data"
#define kTKPDDETAIL_NODATACELLDESCS @"no data description"

#define kTKPDREVIEW_ALERTRATINGLISTARRAY @[@"Average Quality Rating", @"Average Accuracy Rating"]

#define kTKPDREVIEW_ALERTPERIODSARRAY @[@"All The Times", @"6 Months"]
#define kTKPDREVIEW_ALERTPERIODSVALUEARRAY @[@(0), @(6)]

#define kTKPDSHOP_APIETALASENAMEKEY @"etalase_name"
#define kTKPDSHOP_APIETALASEIDKEY @"etalase_id"
#define kTKPDSHOP_APIETALASETOTALPRODUCTKEY @"etalase_total_product"

#define kTKPDSHOP_ETALASEARRAY @[@{kTKPDSHOP_APIETALASENAMEKEY:@"Produk Terjual",kTKPDSHOP_APIETALASEIDKEY:@(7)}, @{kTKPDSHOP_APIETALASENAMEKEY:@"All Etalase",kTKPDSHOP_APIETALASEIDKEY:@(0)}]

#define kTKPDDETAILCATALOG_CACHEFILEPATH @"catalog"
#define kTKPDDETAILSHOP_CACHEFILEPATH @"shop"
#define kTKPDDETAILPRODUCT_CACHEFILEPATH @"product"
#define kTKPDDETAILETALASE_CACHEFILEPATH @"etalase"

#define kTKPDDETAILSHOPETALASE_APIRESPONSEFILE @"etalase"

#define kTKPDDETAILPRODUCT_APIRESPONSEFILEFORMAT @"productdetail%d"
#define kTKPDDETAILPRODUCTTALK_APIRESPONSEFILEFORMAT @"producttalk%d"
#define kTKPDDETAILPRODUCTTALKDETAIL_APIRESPONSEFILEFORMAT @"producttalkdetail%d"
#define kTKPDDETAILPRODUCTREVIEW_APIRESPONSEFILEFORMAT @"productreview%d"

#define kTKPDDETAILSHOP_APIRESPONSEFILEFORMAT @"shopdetail%d"
#define kTKPDDETAILSHOPPRODUCT_APIRESPONSEFILEFORMAT @"shopproduct%d"
#define kTKPDDETAILSHOPTALK_APIRESPONSEFILEFORMAT @"shoptalk%d"
#define kTKPDDETAILSHOPREVIEW_APIRESPONSEFILEFORMAT @"shopreview%d"
#define kTKPDDETAILSHOPNOTES_APIRESPONSEFILEFORMAT @"shopnotes%d"
#define kTKPDDETAILSHOPFAVORITED_APIRESPONSEFILEFORMAT @"shopfavorited%d"
#define kTKPDDETAILSHOPNOTEDETAIL_APIRESPONSEFILEFORMAT @"shopnotedetail%d"

#define kTKPDDETAILCATALOG_APIRESPONSEFILEFORMAT @"catalogdetail%d.plist"

#endif
