//
//  AddressPage.swift
//  Tokopedia
//
//  Created by Julius Gonawan on 10/12/17.
//  Copyright © 2017 TOKOPEDIA. All rights reserved.
//

import Foundation
import XCTest

class AddressPage : Page, TokopediaTabBar {


}

class AddAddress : AddressPage {
 
    let addEditTable = app.tables["addEditTable"]
    let receivedName = app.textFields["receivedName"]
    let addressAs = app.textFields["addressAs"]
    let map = app.buttons["map"]
    let address = app.textViews["address"]
    let postalCode = app.textFields["postalCode"]
    let province = app.buttons["province"]
    let city = app.buttons["city"]
    let district = app.buttons["district"]
    let telephone = app.textFields["telephone"]
    
    let provinceCell = app.tables.cells.staticTexts["DKI Jakarta"]
    let cityCell = app.tables.cells.staticTexts["Jakarta Selatan"]
    let districtCell = app.tables.cells.staticTexts["Setiabudi"]
    let chooseButton = app.buttons["Pilih"]
    let saveButton = app.buttons["Simpan"]
    
    func waitPageLoaded() {
        waitFor(element: addEditTable, status: .Exists)
    }
    
    func fillAddress() {
        waitPageLoaded()
        receivedName.tap()
        receivedName.typeText("default")
        addressAs.tap()
        addressAs.typeText("default")
        address.tap()
        address.typeText("this address was generated by automation machine, keep calm ya, don't panic")
        postalCode.tap()
        postalCode.typeText("12940")
        
        province.tap()
        waitFor(element: provinceCell, status: .Exists)
        provinceCell.tap()
        chooseButton.tap()
        
        city.tap()
        waitFor(element: cityCell, status: .Exists)
        cityCell.tap()
        chooseButton.tap()
        
        district.tap()
        waitFor(element: districtCell, status: .Exists)
        districtCell.tap()
        chooseButton.tap()
        
        telephone.tap()
        telephone.typeText("02143648253")
        
        saveButton.tap()
    }
    
 }

