fastlane_version "1.90.0"

default_platform :ios

def build_app
  project_file = 'Tokopedia.xcodeproj'
  increment_build_number(xcodeproj: project_file)

  gym(scheme: "Tokopedia")  

  commit_version_bump(
    message: 'Version Bump by fastlane',
    xcodeproj: project_file,
    force: true
  )

end

platform :ios do
  before_all do
    ensure_git_status_clean
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    build_app
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    gym(scheme: "Tokopedia")
    deliver(
      force: true,
      skip_deploy: true
    )
  end

  after_all do |lane|
    slack(
       message: "Successfully deployed new App Update."
    )

    clean_build_artifacts
  end

  error do |lane, exception|
    slack(
       message: exception.message,
       success: false
    )
  end
end


