fastlane_version "1.90.0"

default_platform :ios

def build_app
  #increment_build_number(xcodeproj: project_file)
  build_number = Time.new.strftime("%Y%m%d%H%M")
  increment_build_number build_number: build_number

  gym(scheme: "Tokopedia", clean: true, sdk: "iphoneos")

  commit_version_bump(
    message: 'Version Bump by fastlane',
    xcodeproj: ENV["APP_XCODEPROJ"],
    force: true
  )

end

platform :ios do
  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["APP_XCODEPROJ"] = 'ios/Tokopedia.xcodeproj'

    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    build_number = Time.new.strftime("%Y%m%d%H%M")
    increment_build_number({
        xcodeproj: ENV["APP_XCODEPROJ"],
        build_number: build_number
    })

    commit_version_bump(
      message: 'Version Bump by fastlane',
      xcodeproj: ENV["APP_XCODEPROJ"],
      force: true
    )

    cert
    
    sigh(
      provisioning_name: 'com.tokopedia.Tokopedia AppStore',
      ignore_profiles_with_different_name: true,
      filename: 'main.mobileprovision'
    )
    
    sigh(
      app_identifier: 'com.tokopedia.Tokopedia.ServiceExtension',
      provisioning_name: 'com.tokopedia.Tokopedia.ServiceExtension AppStore',
      ignore_profiles_with_different_name: true,
      filename: 'service.mobileprovision'
    )

    disable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])

    update_project_provisioning(
        xcodeproj: ENV["APP_XCODEPROJ"],
        target_filter: 'Tokopedia',
        profile: './main.mobileprovision'
      )

    update_project_provisioning(
      xcodeproj: ENV["APP_XCODEPROJ"],
      target_filter: 'ServiceExtension',
      profile: './service.mobileprovision'
    )

    gym(
      clean: true,
      workspace: 'ios/Tokopedia.xcworkspace',
      scheme: "Tokopedia",
      sdk: "iphoneos",
      codesigning_identity: "iPhone Distribution: TOKOPEDIA PT (YQP4A2M94J)",
      export_method: "app-store"
    )
    
    upload_symbols_to_crashlytics(dsym_path: lane_context[SharedValues::DSYM_OUTPUT_PATH], binary_path: 'ios/Pods/Fabric/upload-symbols', api_token: ENV["CRASHLYTICS_API_KEY"])
    
    pilot(
       skip_submission: false,
       distribute_external: false,
       changelog: changelogs
      )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    build_app
    deliver(
      force: true,
      skip_deploy: true
    )
  end

  lane :devel do
    scheme = 'Tokopedia'

    increment_version_number_in_plist(
      version_number: current_version + "-" + ENV['CIRCLE_BRANCH'] + "." + ENV['CIRCLE_BUILD_NUM'],
      xcodeproj: ENV["APP_XCODEPROJ"],
      scheme: scheme
    )

    cert(development: true)
    
    sigh(
      development: true,
      provisioning_name: 'Hockeyapp Devel',
      ignore_profiles_with_different_name: true,
    )
    
    sigh(
      development: true, 
      app_identifier: 'com.tokopedia.Tokopedia.ServiceExtension',
      provisioning_name: 'Hockeyapp Devel ServiceExtension',
      ignore_profiles_with_different_name: true,
    )

    disable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])

    update_project_provisioning(
      xcodeproj: ENV["APP_XCODEPROJ"],
      target_filter: 'Tokopedia',
      profile: './Development_com.tokopedia.Tokopedia.mobileprovision'
    )

    update_project_provisioning(
      xcodeproj: ENV["APP_XCODEPROJ"],
      target_filter: 'ServiceExtension',
      profile: './Development_com.tokopedia.Tokopedia.ServiceExtension.mobileprovision'
    )

    gym(
      clean: true,
      workspace: 'ios/Tokopedia.xcworkspace',
      scheme: scheme,
      configuration: 'Debug',
      sdk: "iphoneos",
      codesigning_identity: "iPhone Developer: Melissa Juminto (TT6A3N9KTC)",
      export_method: "development"
    )

    hockeyapp
  end

  # Push to Hockey
  def hockeyapp
    hockey(
      api_token: ENV['HOCKEY_API_TOKEN'],
      notes: changelogs
    )
  end

  def current_version
    get_version_number_from_plist(xcodeproj: ENV["APP_XCODEPROJ"], scheme: 'Tokopedia')
  end

  def changelogs
    [
      ENV['CIRCLE_BRANCH'],
      changelog_from_git_commits(commits_count: 10, pretty: "\r\n• %s")
    ].join("\r\n")
  end

  after_all do |lane|
    slack(
       message: "Successfully deployed new App Update."
    )

    clean_build_artifacts
  end

  error do |lane, exception|
    slack(
       message: exception.message,
       success: false
    )
  end
end
