//
//  RegisterTest.swift
//  Tokopedia
//
//  Created by nakama on 8/14/17.
//  Copyright © 2017 TOKOPEDIA. All rights reserved.
//

import XCTest

class RegisterTest: XCTestCase {
    
    var homePage : HomePage = HomePage()
    var feed : FeedPage = FeedPage()
   
    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        Page.app.launch()
        UITest.sharedInstance.testCase = self
        if onBoarding.isOnBoarding() {
            onBoarding.skipOnBoarding()
        }
        if homePage.isUserLogin(){
            homePage.goMorePage().doLogout()
        }
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    func testRegister(){
        let register = homePage.goLoginPage().goToRegister()
        let registerWithEmail = register.registerWithEmail().fillRegisterForm(email: "autogenerated@okeee.com", name: "auto generated", handphone: "081243243244", password: "autogenerated")
        waitFor(element: registerWithEmail.accountActivationView, status: .Exists)
        XCTAssert(registerWithEmail.accountActivationView.exists)
    }

    func testLoginFromRegister() {
        let register = homePage.goLoginPage().goToRegister()
        register.registerWithEmail().fillRegisterForm(email: "julius.gonawan+automationbuyer@tokopedia.com", name: "auto generated", handphone: "08121111313", password: "tokopedia2016")
        waitFor(element: feed.feedTab, status: .Exists)
        XCTAssert(feed.feedTab.exists)
    }

    func testResetPasswordRegister() {
        let register = homePage.goLoginPage().goToRegister()
        let registerWithEmail = register.registerWithEmail().fillRegisterForm(email: "julius.gonawan+automationbuyer@tokopedia.com", name: "auto generated", handphone: "08121111313", password: "tokopedia201d6")
        waitFor(element: registerWithEmail.resetPasswordView , status: .Exists)
        XCTAssert(registerWithEmail.resetPasswordView.exists)
    }
    
}


