//
//  AnalyticsString.h
//  Tokopedia
//
//  Created by Kenneth Vincent on 10/4/16.
//  Copyright © 2016 TOKOPEDIA. All rights reserved.
//

#ifndef AnalyticsString_h
#define AnalyticsString_h

#pragma mark - Event Category
#define GA_EVENT_CATEGORY_HOMEPAGE @"Homepage"
#define GA_EVENT_CATEGORY_SEARCH @"Search"
#define GA_EVENT_CATEGORY_SEARCH_RESULT @"Search Result"
#define GA_EVENT_CATEGORY_NO_SEARCH_RESULT @"No Search Result"
#define GA_EVENT_CATEGORY_SORT @"Sort"
#define GA_EVENT_CATEGORY_FILTER @"Filter"
#define GA_EVENT_CATEGORY_HOTLIST @"Hotlist"
#define GA_EVENT_CATEGORY_WISHLIST @"Wishlist"
#define GA_EVENT_CATEGORY_FEED @"Feed"
#define GA_EVENT_CATEGORY_RECENTLY_VIEWED @"Recently Viewed"
#define GA_EVENT_CATEGORY_FAVORITE @"Favorite"
#define GA_EVENT_CATEGORY_SNAP_SEARCH @"Snap Search"
#define GA_EVENT_CATEGORY_PRODUCT_DETAIL_PAGE @"Product Detail Page"
#define GA_EVENT_CATEGORY_INBOX_MESSAGE @"Message"
#define GA_EVENT_CATEGORY_INBOX_TALK @"Product Discussion"
#define GA_EVENT_CATEGORY_INBOX_REVIEW @"Review"
#define GA_EVENT_CATEGORY_INBOX_TICKET @"Help"
#define GA_EVENT_CATEGORY_INBOX_RESOLUTION @"Resolution"
#define GA_EVENT_CATEGORY_ATC @"Add to Cart"
#define GA_EVENT_CATEGORY_CHECKOUT @"Checkout"
#define GA_EVENT_CATEGORY_PAYMENT @"Payment"
#define GA_EVENT_CATEGORY_SALES @"Sales"
#define GA_EVENT_CATEGORY_NEW_ORDER @"New Order"
#define GA_EVENT_CATEGORY_SHIPPING @"Shipping"
#define GA_EVENT_CATEGORY_ORDER_STATUS @"Status"
#define GA_EVENT_CATEGORY_TRANSACTION @"Transaction"
#define GA_EVENT_CATEGORY_RECEIVED @"Received"
#define GA_EVENT_CATEGORY_SHOP_HOME @"Shop Home"
#define GA_EVENT_CATEGORY_SHOP_SETTINGS @"Manage Shop"
#define GA_EVENT_CATEGORY_SHOP_INFO @"Shop Info"
#define GA_EVENT_CATEGORY_ETALASE @"Etalase"
#define GA_EVENT_CATEGORY_SHOP_PRODUCT @"Product"
#define GA_EVENT_CATEGORY_SHOP_LOCATION @"Location"
#define GA_EVENT_CATEGORY_SHOP_SHIPPING @"Shipping"
#define GA_EVENT_CATEGORY_SHOP_NOTES @"Notes"
#define GA_EVENT_CATEGORY_CREATE_SHOP @"Create Shop"
#define GA_EVENT_CATEGORY_TAB_BAR @"Tab Bar"
#define GA_EVENT_CATEGORY_NOTIFICATION @"Toped Icon"
#define GA_EVENT_CATEGORY_MORE @"More"
#define GA_EVENT_CATEGORY_REGISTER @"Register"
#define GA_EVENT_CATEGORY_LOGIN @"Login"
#define GA_EVENT_CATEGORY_CARDIO_SCAN @"Card IO Scan"
#define GA_EVENT_CATEGORY_FORGOT_PASSWORD @"Forgot Password"
#define GA_EVENT_CATEGORY_SECURITY_QUESTION @"Security Question"
#define GA_EVENT_CATEGORY_CREATE_SHOP @"Create Shop"
#define GA_EVENT_CATEGORY_SEARCH_RESULT @"Search Result"
#define GA_EVENT_CATEGORY_SALES @"Sales"
#define GA_EVENT_CATEGORY_NEW_ORDER @"New Order"
#define GA_EVENT_CATEGORY_SHIPMENT_CONFIRMATION @"Shipping"
#define GA_EVENT_CATEGORY_SHIPMENT_STATUS @"Status"
#define GA_EVENT_CATEGORY_TRANSACTION_LIST @"Transaction"
#define GA_EVENT_CATEGORY_RECEIVED @"Received"
#define GA_EVENT_CATEGORY_TRACKING @"Tracking"

#pragma mark - Event Action
#define GA_EVENT_ACTION_CLICK @"Click"
#define GA_EVENT_ACTION_VIEW @"View"
#define GA_EVENT_ACTION_SEND @"Send"
#define GA_EVENT_ACTION_ERROR @"Error"
#define GA_EVENT_ACTION_ABANDON @"Abandon"
#define GA_EVENT_ACTION_EDIT @"Edit"
#define GA_EVENT_ACTION_COPY @"Copy"
#define GA_EVENT_ACTION_SEARCH @"Search"
#define GA_EVENT_ACTION_SEARCH_HISTORY @"Search History"
#define GA_EVENT_ACTION_SEARCH_HOTLIST @"Search Hotlist"
#define GA_EVENT_ACTION_SEARCH_AUTOCOMPLETE @"Search Autocomplete"
#define GA_EVENT_ACTION_POPULAR_SEARCH @"Popular Search"
#define GA_EVENT_ACTION_CATEGORY @"Category"
#define GA_EVENT_ACTION_NO_RESULT @"No Result"
#define GA_EVENT_ACTION_REPORT_SUCCESS @"Report Success"
#define GA_EVENT_ACTION_ADD_ADDRESS_SUCCESS @"Add Address Success"
#define GA_EVENT_ACTION_ADD_ADDRESS_ABANDON @"Add Address Abandon"
#define GA_EVENT_ACTION_ATC_ABANDON @"Add to Cart Abandon"
#define GA_EVENT_ACTION_ATC_ERROR @"Add to Cart Error"
#define GA_EVENT_ACTION_REGISTER_SUCCESS @"Register Success"
#define GA_EVENT_ACTION_REGISTER_ERROR @"Error"
#define GA_EVENT_ACTION_REGISTER @"Register"
#define GA_EVENT_ACTION_LOGIN_SUCCESS @"Login Success"
#define GA_EVENT_ACTION_LOGIN_ERROR @"Login Error"
#define GA_EVENT_ACTION_RESET_SUCCESS @"Reset Success"
#define GA_EVENT_ACTION_OTP_SUCCESS @"OTP Success"

#endif /* AnalyticsString_h */
